### ISSUE TITLE
[IDEA/Question] How much thought went into emulating RL with a barebones model?

### ISSUE THREAD

**Issue by tursi960** [Rolv-Arild/Necto#16]
I don't want to sound presumptuous because I'm far from an expect but wouldn't a physics emulation without graphics allow for a simultaneous training of say 10,000 games at once instead of like 50?

That AI wouldn't be working straight off but if you have a decent emulation wouldn't the bot have a huge head start after a minor adaptation phase?

Would this be of interest if I decide to pursue this further?

**Comment by humble-leo** [comment]
you wont pursue this because emulating correct rl physics is not in your league.

heres some links for you to see what youre getting yourself into:
https://github.com/roboserg/RoboLeague - original
https://github.com/PG642/Rocket-League-Unity-Simulation - updated
https://arxiv.org/pdf/2205.05061.pdf

![image](https://user-images.githubusercontent.com/102901194/212388783-df508a63-d3c4-4151-8004-32e95e27ee4a.png)
![image](https://user-images.githubusercontent.com/102901194/212388840-c5a9167e-8ebb-4360-9141-e3c2f24ba03a.png)
https://www.youtube.com/watch?v=8k9FNxIU0KQ

**Comment by tursi960** [comment]
Thank you for the answer. This is exactly what I was looking for.
