### ISSUE TITLE
Pre-normalization question

### ISSUE THREAD

**Issue by abhimasand** [Rolv-Arild/Necto#5]
Why does demo time consider 120 fps ? 

The observation builder has a comment in front of the demo timer  (Pre-normalized, 120 fps for 10 seconds). However, if the game speed is set to 100, the documentation of rlgym vaguely states that it will run at 240 fps, so why are we considering 120 fps here? 

[Observation builder file](https://github.com/Rolv-Arild/Necto/blob/master/training/obs.py#L85)
`self.boost_timers -= self.tick_skip / 1200  # Pre-normalized, 120 fps for 10 seconds`

[RLGym reference](https://github.com/lucas-emery/rocket-league-gym/blob/7d8e37809126f6702c5f433e7dafdc3aedde4033/rlgym/make.py#L27)
`:param game_speed: The speed the physics will run at, leave it at 100 unless your game can't run at over 240fps`

**Comment by nevercast** [comment]
Hi Mashex,

The reason is that the boost timers run on in-game time* so while running at `game_speed=2` would mean 240 physics ticks per second instead of 120 physics ticks per second, game time would also increase at 2 seconds per real second. 

The confusion here is that the "fps" in Observation Builder is game time, and the "fps" in RLGym is real time. 

Why "240fps" is in the reference, is not clear to me. At a tick_skip of 0 and a game_speed of 1, I would expect 120fps (or tps, ticks per second, rendered frames aren't really relevant here)

* (approximately, there is some skew when running the game faster but ignore that as it's negligible).

**Comment by Rolv-Arild** [comment]
Hello, sorry for the late reply.

Rocket League runs at 120 ticks per second, which is the source of the value in obs builder. The RLGym comment just refers to having a computer that can run the game fast enough to do the required physics substeps in time, otherwise slight inaccuracies may occur.
